#!/usr/bin/env python3
"""Fail-closed checks for the exact, source-controlled public plugin tree.

This checker is intentionally local and standard-library-only.  It validates
the tree that it is given; it never exports, contacts GitHub, or mutates the
tree.
"""

from __future__ import annotations

import ast
import json
import os
import re
import stat
import sys
from pathlib import Path, PurePosixPath
from typing import Any

sys.dont_write_bytecode = True

MANIFEST_RELATIVE = "skills/codex-model-router/references/public-file-manifest.json"
PLUGIN_MANIFEST_RELATIVE = ".codex-plugin/plugin.json"
SKILL_RELATIVE = "skills/codex-model-router/SKILL.md"
DEPENDENCIES_RELATIVE = "docs/dependencies.md"

_CACHE_NAMES = {
    "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache", ".cache",
    ".tox", ".venv", "venv", "node_modules",
}
_FORBIDDEN_COMPONENTS = {
    ".superpowers", "baseline-evals", "behavior-evals", "semantic-evals", "forward-evals",
}
_CAMPAIGN_COMPONENTS = {
    "campaign", "campaigns", "eval", "evals", "evaluation", "evaluations", "run", "runs",
}
_PRIVATE_COMPONENTS = {
    "private", "private-data", "private-evidence", "quality-first-routing-dev", "quality-first-routing-private",
}
_PAYLOAD_COMPONENTS = {
    "evidence", "raw", "transcript", "transcripts", "invocation", "invocations", "score", "scores", "ledger", "ledgers",
}
_SECRET_PATTERNS = (
    re.compile(r"\bghp_[A-Za-z0-9]{30,}\b"),
    re.compile(r"\bgithub_pat_[A-Za-z0-9_]{30,}\b"),
    re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b"),
    re.compile(r"\bsk-[A-Za-z0-9_-]{20,}\b"),
    re.compile(r"\bAKIA[0-9A-Z]{16}\b"),
    re.compile(r"(?i)\bbearer\s+[A-Za-z0-9._~-]{24,}\b"),
    re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----"),
)
_MAC_USER_PATH = re.compile(r"/(?:Users|home)/[^/\s]+(?:/|$)")
_WINDOWS_USER_PATH = re.compile(r"(?i)\b[A-Z]:[\\/](?:Users|home)[\\/][^\\/\s]+")
_STDLIB = set(getattr(sys, "stdlib_module_names", ()))
_STDLIB.update(
    {
        "__future__", "argparse", "ast", "collections", "dataclasses", "functools", "hashlib",
        "importlib", "itertools", "json", "math", "os", "pathlib", "re", "shutil", "stat",
        "subprocess", "sys", "tempfile", "textwrap", "time", "typing", "unittest", "urllib",
    }
)
_LOCAL_MODULES = {"cmr_compiler", "cmr_contracts", "cmr_dispatch", "cmr_runtime", "qfr_legacy", "support"}


def _error(message: str, errors: list[str]) -> None:
    errors.append(message)


def _relative(path: Path, root: Path) -> str:
    return path.relative_to(root).as_posix()


def _path_errors(relative: str) -> list[str]:
    errors: list[str] = []
    path = PurePosixPath(relative)
    parts = tuple(path.parts)
    lower = tuple(part.casefold() for part in parts)
    if relative.startswith("/") or "\\" in relative or ".." in path.parts:
        errors.append(f"path is not normalized relative POSIX: {relative}")
    if any(part in _CACHE_NAMES for part in lower) or relative.endswith((".pyc", ".pyo")):
        errors.append(f"cache or generated bytecode is not public: {relative}")
    if any(part in _FORBIDDEN_COMPONENTS for part in lower):
        errors.append(f"forbidden private evidence path: {relative}")
    if any(part in _PRIVATE_COMPONENTS for part in lower):
        errors.append(f"private development repository path: {relative}")
    if path.name.casefold().endswith("-oracle.json") or path.name.casefold().endswith("-score.json"):
        errors.append(f"private oracle or score file: {relative}")
    if set(lower) & _CAMPAIGN_COMPONENTS and set(lower) & _PAYLOAD_COMPONENTS:
        errors.append(f"campaign payload directory is not public: {relative}")
    return errors


def _walk(root: Path, errors: list[str]) -> list[Path]:
    files: list[Path] = []
    try:
        root_stat = root.lstat()
    except OSError as exc:
        _error(f"tree cannot be read: {exc}", errors)
        return files
    if not stat.S_ISDIR(root_stat.st_mode):
        _error("tree root must be a directory", errors)
        return files
    for current, directories, names in os.walk(root, topdown=True, followlinks=False):
        current_path = Path(current)
        retained: list[str] = []
        for name in sorted(directories):
            path = current_path / name
            relative = _relative(path, root)
            try:
                mode = path.lstat().st_mode
            except OSError as exc:
                _error(f"cannot stat {relative}: {exc}", errors)
                continue
            if name == ".git":
                if current_path == root and stat.S_ISDIR(mode) and not stat.S_ISLNK(mode):
                    # A destination repository may already have local Git
                    # metadata. Ignore only this one root-level directory.
                    continue
                if current_path == root:
                    _error("root .git metadata must be a real directory: .git", errors)
                else:
                    _error(f"nested .git metadata is not public: {relative}", errors)
                continue
            if stat.S_ISLNK(mode):
                _error(f"symlink is not public: {relative}", errors)
            else:
                _error_list = _path_errors(relative)
                errors.extend(_error_list)
                retained.append(name)
        directories[:] = retained
        for name in sorted(names):
            path = current_path / name
            relative = _relative(path, root)
            try:
                mode = path.lstat().st_mode
            except OSError as exc:
                _error(f"cannot stat {relative}: {exc}", errors)
                continue
            if name == ".git":
                if current_path == root:
                    _error("root .git metadata must be a directory: .git", errors)
                else:
                    _error(f"nested .git metadata is not public: {relative}", errors)
                continue
            if ".git" in PurePosixPath(relative).parts:
                _error(f"nested .git metadata is not public: {relative}", errors)
                continue
            errors.extend(_path_errors(relative))
            if stat.S_ISLNK(mode):
                _error(f"symlink is not public: {relative}", errors)
            elif not stat.S_ISREG(mode):
                _error(f"non-regular file is not public: {relative}", errors)
            else:
                files.append(path)
    return files


def _manifest_paths(root: Path, errors: list[str]) -> list[str]:
    path = root / MANIFEST_RELATIVE
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        _error(f"public file manifest is invalid: {exc}", errors)
        return []
    if not isinstance(value, dict) or value.get("schema_version") != "codex-public-file-manifest-v1":
        _error("public file manifest schema_version is invalid", errors)
        return []
    entries = value.get("files")
    if not isinstance(entries, list):
        _error("public file manifest.files must be an array", errors)
        return []
    paths: list[str] = []
    for index, entry in enumerate(entries):
        if isinstance(entry, str):
            item = entry
        elif isinstance(entry, dict) and isinstance(entry.get("path"), str):
            item = entry["path"]
        else:
            _error(f"public file manifest entry {index} is invalid", errors)
            continue
        paths.append(item)
        errors.extend(_path_errors(item))
    if len(paths) != len(set(paths)):
        _error("public file manifest contains duplicate paths", errors)
    return paths


def _scan_text(path: Path, relative: str, errors: list[str]) -> None:
    try:
        data = path.read_bytes()
    except OSError as exc:
        _error(f"cannot read {relative}: {exc}", errors)
        return
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError:
        return
    for pattern in _SECRET_PATTERNS:
        if pattern.search(text):
            _error(f"token-like secret in {relative}", errors)
    if _MAC_USER_PATH.search(text) or _WINDOWS_USER_PATH.search(text):
        _error(f"absolute user path in {relative}", errors)
    # This checker necessarily contains its own marker vocabulary. Scan that
    # code for secrets and paths, but do not treat the implementation's
    # literal rule table as a leaked private artifact.
    private_markers = () if relative == "skills/codex-model-router/scripts/check_public_release.py" else (
        ".superpowers/", "baseline-evals/", "behavior-evals/", "semantic-evals/", "forward-evals/", "quality-first-routing-dev"
    )
    if any(marker in text.casefold() for marker in private_markers):
        _error(f"private development marker in {relative}", errors)


def _check_json_files(files: list[Path], root: Path, errors: list[str]) -> None:
    for path in files:
        relative = _relative(path, root)
        if path.suffix.casefold() != ".json":
            continue
        try:
            json.loads(path.read_text(encoding="utf-8"))
        except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
            _error(f"invalid JSON in {relative}: {exc}", errors)


def _check_imports(files: list[Path], root: Path, errors: list[str]) -> None:
    for path in files:
        if path.suffix != ".py":
            continue
        relative = _relative(path, root)
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=relative)
        except (OSError, UnicodeDecodeError, SyntaxError) as exc:
            _error(f"Python source is invalid in {relative}: {exc}", errors)
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names = [alias.name.split(".", 1)[0] for alias in node.names]
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                names = [node.module.split(".", 1)[0]]
            else:
                continue
            for name in names:
                if name not in _STDLIB and name not in _LOCAL_MODULES:
                    _error(f"undeclared non-stdlib import {name} in {relative}", errors)


def _check_cross_file_contracts(root: Path, errors: list[str]) -> None:
    plugin_path = root / PLUGIN_MANIFEST_RELATIVE
    try:
        plugin = json.loads(plugin_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        _error(f"plugin manifest is invalid: {exc}", errors)
        plugin = {}
    if isinstance(plugin, dict):
        if plugin.get("name") != "codex-model-router":
            _error("plugin manifest name must be codex-model-router", errors)
        if plugin.get("version") != "0.4.0":
            _error("plugin manifest version must be 0.4.0", errors)
        if plugin.get("license") != "Apache-2.0":
            _error("plugin manifest license must be Apache-2.0", errors)
        interface = plugin.get("interface")
        if not isinstance(interface, dict) or interface.get("displayName") != "Codex Model Router":
            _error("plugin manifest interface displayName is invalid", errors)
    skill_path = root / SKILL_RELATIVE
    try:
        frontmatter = skill_path.read_text(encoding="utf-8").split("---", 2)
        name_line = next(line for line in frontmatter[1].splitlines() if line.startswith("name:"))
        skill_name = name_line.split(":", 1)[1].strip()
        if skill_name != "codex-model-router":
            _error("skill frontmatter name must be codex-model-router", errors)
    except (OSError, UnicodeDecodeError, StopIteration, IndexError) as exc:
        _error(f"skill metadata is invalid: {exc}", errors)
    try:
        dependency_text = (root / DEPENDENCIES_RELATIVE).read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        _error(f"dependency documentation is missing: {exc}", errors)
    else:
        required = ("gpt-5.6-luna", "gpt-5.6-sol", "xhigh", "max", "Superpowers 6.3.0", "Python 3.10", "standard library", "Git", "GitHub CLI")
        for phrase in required:
            if phrase.casefold() not in dependency_text.casefold():
                _error(f"dependency documentation omits {phrase}", errors)
    try:
        license_text = (root / "LICENSE").read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        _error(f"Apache license is missing: {exc}", errors)
    else:
        if "Apache License" not in license_text or "Version 2.0" not in license_text:
            _error("LICENSE is not Apache-2.0 text", errors)


def check_tree(root: Path) -> list[str]:
    errors: list[str] = []
    root = root.resolve()
    files = _walk(root, errors)
    actual = sorted(_relative(path, root) for path in files)
    manifest = sorted(_manifest_paths(root, errors))
    if actual != manifest:
        missing = sorted(set(manifest) - set(actual))
        unlisted = sorted(set(actual) - set(manifest))
        if missing:
            _error(f"manifest lists missing file(s): {', '.join(missing)}", errors)
        if unlisted:
            _error(f"unlisted file(s): {', '.join(unlisted)}", errors)
    for path in files:
        _scan_text(path, _relative(path, root), errors)
    _check_json_files(files, root, errors)
    _check_imports(files, root, errors)
    _check_cross_file_contracts(root, errors)
    return sorted(set(errors))


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]
    if len(argv) != 1:
        result = {"valid": False, "errors": ["usage: check_public_release.py TREE"]}
        print(json.dumps(result, separators=(",", ":")))
        return 1
    errors = check_tree(Path(argv[0]))
    result: dict[str, Any] = {"valid": not errors, "errors": errors}
    print(json.dumps(result, ensure_ascii=False, separators=(",", ":"), sort_keys=True))
    if errors:
        print(f"public release rejected: {errors[0]}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
